name: netcdf_python
channels:
  - conda-forge
dependencies:
  - python=3.12
  - xarray
  - netcdf4
  - h5netcdf
  - h5py
  - cftime
  - matplotlib
  - jupyterlab
  - scipy
  - pandas
  - requests
  - requests_cache
  - beautifulsoup4
  - lxml
  - Webob
  - pip
  - pydap=3.5.2
  - pydap-server
  - pip:
      - cf_xarray
      - numpy
      
    

